site_name : OSGL Genie Documentation
site_description: A JSR 330 dependency injection library

repo_url: https://github.com/osglworks/java-di/

docs_dir: doc/

theme: readthedocs

pages:
- 'Home' : 'index.md'

- 'Getting Started' : 'getting_start.md'
- 'Binding' : 'binding.md'
- 'Scoping' : 'scope.md'

- Features:
  - 'Inject collection' : 'container.md#inject-into-collection'
  - 'Filter collection elements' : 'container.md#filtering'
  - 'Inject map' : 'container.md#inject-map-type-bean'
  - 'Built-in element loaders' : 'container.md#built-in-elementloaders'
  - 'Inject value' : 'value.md'

- Samples:
  - 'Implement Spring 4.3 style InjectionPoint style binding' : 'https://github.com/greenlaw110/hello-genie-injectionPoint'
  - 'Implement Spring 4.3 style customized annotation' : 'https://github.com/greenlaw110/genie-custom-annotation-demo'

- 'Performance Benchmark' : 'performance.md'