site_name : OSGL Genie Documentation
site_description: A JSR 330 dependency injection library

repo_url: https://github.com/osglworks/java-di/

docs_dir: doc/

theme: readthedocs

pages:
- 'Home' : 'index.md'

- 'Getting Started' : 'getting_start.md'
- 'Binding' : 'binding.md'
- 'Inject collection and map' : 'container.md'
- 'Inject value' : 'value.md'
- 'Scoping' : 'scope.md'

- Samples:
  - 'Implement Spring 4.3 style InjectionPoint style binding' : 'https://github.com/greenlaw110/hello-genie-injectionPoint'
  - 'Implement Spring 4.3 style customized annotation' : 'https://github.com/greenlaw110/genie-custom-annotation-demo'

- 'Performance Benchmark' : 'performance.md'